### ISSUE TITLE
Milestone 1 Remaining Tasks

### ISSUE THREAD

**Issue by slbsolomon** [UBC-MDS/DSCI_522_GROUP_312#1]
Everyone is to have a pull request with a draft sent by Friday, Jan 17th at 6PM.

Tasks:
@EitharAlfatih
- README document
- Proposal: Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already know how to do (report an estimate and confidence intervals, a two-group hypothesis, linear regression, classification with a decision tree, etc).
- EDA Script (1/2)

@slbsolomon 
- contributing file
- EDA Script (1/2)
- Proposal: Discuss at least one exploratory data analysis table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.

@gptzjs 
- teamwork contract (add Friday 6PM deadline, team meetings on Tuesdays after lab)
- Proposal: With your data set, identify one main predictive or inferential research question that you will attempt to answer with analyses and visualizations (more on this below). Clearly state the research question and any natural sub-questions you need to address, and their type. The main research question should be either predictive or inferential, as discussed in Lecture 1.
- Proposal: Suggest how you would share the results of your analysis as one or more tables and/or figures.
- Script to download and save data

**Comment by gptzjs** [comment]
All tasks completed Nice work team!
