### ISSUE TITLE
Milestone 2 Work Splits

### ISSUE THREAD

**Issue by slbsolomon** [UBC-MDS/DSCI_522_GROUP_312#20]
1. Load Data Script (Wednesday 9PM) - George to make updates as needed with feedback
2. Data cleaning (Wednesday 9PM) - R - Samantha
3. EDA tables/graphs (Friday noon) - George
4. stat/ML analysis (Friday noon) - Eithar
5. presents all EDA (Friday 6PM) - Samantha

**Comment by gptzjs** [comment]
All agreed as discussed. Hope we get the feedback soon!
