### ISSUE TITLE
Analysis plan needs detail

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#22]
There are several areas which need more detail in the analysis plan - it should be more concrete and have action steps in order. For example: 

- "We will use Linear Regression, K-Nearest Neighbour Trees, and other methods as we see fit" - pick one or more methods and explain why you picked them!
- Explain more aspects of your analysis plan eg "multicollinearity issue" - what is this issue?
- It's great that you're building on someone else's analysis, but:
  - You need to explain what Geron did
  - You need to be clear about whether you're trying to make a better linear regression than his, or find a different model he didn't implement but that works better (eg K-Nearest Neighbour Trees).
- What model metric is used for tuning hyperparameters?
- You say "Geron's analysis concluded that linear regression was the best estimator" but Linear regression is a model, not an estimator

**Comment by slbsolomon** [comment]
Hi Kate,

Thank you for the feedback. These items have been addressed here: https://github.com/UBC-MDS/DSCI_522_GROUP_312/pull/26 

We will close this issue, but please feel free to re-open if you believe anything needs more work.
