### ISSUE TITLE
File directory structure

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#23]
Having a separate script to make several images for the EDA is not bad and in fact can be good pipelining! However there are two things you could do to improve this setup:

1. Have the stript that makes plots for your EDA use the datafile you downloaded using your other script, rather than reading the data off the web again. (The pipleline then goes download script -> EDA plot script -> EDA notebook.)
2. You can make a subfolder in the eda folder to contain the extra image files.

**Comment by slbsolomon** [comment]
Hi Kate,

This is resolved now as everything has been moved to scripts.
