### ISSUE TITLE
Process/communications feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#30]
From most important to fix to minor considerations:

- Make sure you merge pull requests - it looks like "George" is committing directly frequently.
- Some commit messages could be more descriptive, eg "scripts updated" and "update README"
- You have two contributing documents, which is confusing. Your work contract also shouldn't really be in the public repo. NOTE: looking at the current version, you appear to have removed the work contract - but also BOTH of the contributing documents. Leave one contributing!
- Could have more back and forth in issues as opposed to just posting tasks
- Team work contract refers to app.py but is otherwise excellent

**Comment by slbsolomon** [comment]
Hi Kate,

- Per our team contract, George should not be directly committing. I believe this was resolved for Milestone 2.
- Our group will work on having more descriptive commit messages
- One contributing doc was re-added
- We will aim to work more in issues
- @gptzjs may you please update the teamwork contract and then close this issue?

**Comment by gptzjs** [comment]
Hi Kate,

Thanks for the feedback which we will definitely address. 

I will send the updated Team_Contract.md file in an issues attachment for the rest of the team to save to their private repos.

Thanks!
George
