### ISSUE TITLE
Updated Team_Contract.md

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_522_GROUP_312#38]
Team, 

I have corrected the typo in the file which is attached since it should not be on this public repo.

Note also that we are unable to push this to the milestone1 but please keep for reference.
[Team_Contract.md.zip](https://github.com/UBC-MDS/DSCI_522_GROUP_312/files/4118070/Team_Contract.md.zip)

Thanks!
GT

**Comment by slbsolomon** [comment]
Thanks George - looks good to me!
