### ISSUE TITLE
Tests needed!

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#41]
- Need at least one test in download, EDA, ML scripts
- Wrangling test doesn't work - you don't actually call your test function - to do so use test_files_created() with parenthesis

**Comment by gptzjs** [comment]
I will re-create the test in the load_data.py script which was there in the original version but somehow got deleted before we pushed.

**Comment by slbsolomon** [comment]
Updated in #50 - the test function wasn't working because I was using variables that didn't exist outside of the main function - to fix this, I put the test_that call inside of the main function, and it appears to be working now.

**Comment by slbsolomon** [comment]
@EitharAlfatih added tests to the ML script earlier, and I added tests to the EDA script in #52.
