### ISSUE TITLE
Documentation: minor fixes!

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#42]
- Download documentation should include example URLs
  - I'm a bit confused by this - my previous issue says it was fixed but now it's gone and I can't see the change in the commits.
- Wrangling script documentation should give the split used
- In-code comments are good, especially EDA and ML!

**Comment by slbsolomon** [comment]
Updated in #50 - the wrangling script documentation was updated to reflect that we split our data 80/20.

The download documentation has the sample in the README - does it need to be in the load_data.py script?

**Comment by ksedivyhaley** [comment]
It is best to have it in both places, because that way if someone is looking at the script documentation directly they can easily see the defaults. This happens if for example they use the wrong arguments in calling the script.

That said, for a project like this, the README is the most important place for that information. It is more important to have it directly in the script in the event that you are making for example an R package (because that documentation will be easily accessible to search and thus more frequently viewed).

**Comment by slbsolomon** [comment]
Agreed with your rationale - for this script we will keep it in the README so I will close this issue. Our url is quite long and points to a different github repo, so it can be confusing and it is quite a large file so requires '?raw=true' for it to work which can also be confusing. Feel free to re-open if you think it will be necessary here.
