### ISSUE TITLE
Report feedback: good, but expand a little

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#43]
- Report descriptions are well done & clear
- Opportunities for improvement could be expanded on
- Having the critique of analysis end with the data on error based on number of neighbours is confusing - separate these points.
- Need to interpret in context of the question (Is this a good model? Does it beat Eric Chen's?) This may involve expanding a bit more on the last table.

**Comment by slbsolomon** [comment]
Updated in #50 - clarified the conclusion, added areas for improvement, and formally answered the research question.
