### ISSUE TITLE
Vizualizations: formatting fixes

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#44]
- Format tables to have nicer column names
  - Alternatively, present these as graphs instead - the second table in particular is a bit difficult to read as-is.
- Format graph labels to be neat (no underscores)
- Correlation plot diagonal should have a colour other than the highest value

**Comment by slbsolomon** [comment]
Assignments:
@gptzjs - may you please work on this one, and if you need help (since Eithar and I originally made these), please let us know

**Comment by gptzjs** [comment]
Thanks Sam, as discussed I will do this and will let you guys know if there are any problems which I don't foresee.

**Comment by slbsolomon** [comment]
Updated in #52 :
- added more human readable labels to the correlation heatmap and other charts
- the correlation heatmap should in fact have perfect correlation diagonally. The correlation of a variable with itself should equal 1. If you have an issue with this, please discuss with Tiffany.

**Comment by ksedivyhaley** [comment]
> Updated in #52 :
> 
> * added more human readable labels to the correlation heatmap and other charts
> * the correlation heatmap should in fact have perfect correlation diagonally. The correlation of a variable with itself should equal 1. If you have an issue with this, please discuss with Tiffany.

@slbsolomon, that's how the math works, but from a visualization point of view it draws the focus of the viewer towards something completely uninformative (correlation of a variable with itself *always* equals one) and away from other high correlations within the matrix. Setting the values of a diagonal to something else before graphing can make the visualization easier to interpret.

On how to implement this, see:

For r: https://stackoverflow.com/questions/27890153/eliminate-the-diagonal-values-in-a-correlation-plot

For python: https://stackoverflow.com/questions/35405222/pandas-how-to-drop-self-correlation-from-correlation-matrix

(Clearly my initial explanation was lacking so I won't expect this implemented in Milestone 3, but it would be nice to include in Milestone 4!)

**Comment by slbsolomon** [comment]
Thanks Kate - re-opened.
@gptzjs re-assigning to you for Milestone 4

**Comment by gptzjs** [comment]
Thanks Kate, will implement your suggestion for milestone 4

**Comment by gptzjs** [comment]
New correlation plot has been created with renamed columns, excluding diagonal and showing only lower triangle for easier interpretation
