### ISSUE TITLE
Script fix: ML path

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#45]
You need to add a `/` to the path when saving the output of the machine learning script - my files ended up in the main results folder as a file titled `ml_resultsrfr_results_table.csv`.

**Comment by slbsolomon** [comment]
Assignments:
You need to add a / to the path when saving the output of the machine learning script - my files ended up in the main results folder as a file titled ml_resultsrfr_results_table.csv. - @slbsolomon

**Comment by slbsolomon** [comment]
Updated in #50 - we added the / to the readme so that this was fixed without hard coding any updates
