### ISSUE TITLE
George's Milestone 3 Peer Feedback

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_522_GROUP_312#48]
- Nice improvement on the original model accuracy from the original 
- Is there another way to encode geographical location other than longitude / latitude of the census block?
- Can you run KNN without longitude / latitude?
- Consider including side-by-side histograms of actual prices and predicted prices?

**Comment by slbsolomon** [comment]
Plan for addressing:
- There isn't a clear way to encode latitude/longitude, but we will address this along with the next point by running knn with a variety of feature selections, which will also address our multicollinearity issue.
- we don't believe that a histogram will be an effective way to display actual vs. predicted prices, but will consider other plot types.

**Comment by slbsolomon** [comment]
Run KNN with feature selection - @EitharAlfatih

**Comment by EitharAlfatih** [comment]
Considering the time complexity of KNN, especially for prediction, the suggested modification will not be implemented. Instead, and since Random Forests are faster for both prediction and fitting, hyperparameter optimization was performed on max_depth and min_samples_leaf.

**Comment by slbsolomon** [comment]
Ended up making specific combinations to run KNN and LR with some feature exclusions to get an idea of the effects of latitude and longitude as well as total rooms. Updated in #52
