### ISSUE TITLE
Eithar's class feedback

### ISSUE THREAD

**Issue by EitharAlfatih** [UBC-MDS/DSCI_522_GROUP_312#49]
*  More interpretable metrics for the analysis results.
* Results in the tables can be better represented using plots.

**Comment by slbsolomon** [comment]
As far as we know, there wouldn't be another appropriate metric for our analysis result that is human-understandbale, but we will add a narrative about our result metrics. We will be adding plots for tables

**Comment by EitharAlfatih** [comment]
Plots are created for both KNN and Logistic Regression performances
