### ISSUE TITLE
Milestone 4 Work Split

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_522_GROUP_312#55]
1. Create Makefile dependency diagram using [makefile2graph](https://github.com/lindenb/makefile2graph) and include image in README (Thu 9 pm) - George

2. Write Dockerfile (Thu 9pm) - George

3. Build Docker image (Thu 9pm) - Eithar

4. Update project README with instructions on using project with and without Docker and estimated completion times for data download and analysis (Fri 6 pm) - Sam

**Comment by gptzjs** [comment]
As discussed, Sam will create the Makefile dependency diagram so we have one person making all the necessary changes to the README

**Comment by slbsolomon** [comment]
Thanks George! Sounds good!

**Comment by slbsolomon** [comment]
Makefile dependency diagram added in #64

**Comment by slbsolomon** [comment]
My work on the README was completed in #74

**Comment by gptzjs** [comment]
All tasks completed
