### ISSUE TITLE
Milestone 3: Mechanics feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#58]
- Your issues based discussion is excellent, particularly making it clear how you were responding to the peer feedback (and in a minority of cases, why you weren't responding to it)

- Your high-level overview in the README should not be the same as your project proposal, though it could use a lot of the same text - you're aiming for a 2 paragraph summary of the objective and main outcome of your project.
- Cite at least one external sources other than data source, languages, and packages.

**Comment by slbsolomon** [comment]
Hi Kate, can you please clarify what kind of external data source you would like to see? For example, we repeatedly reference [Eric Chen's Kernel](https://www.kaggle.com/ericfeng84/housing-price-prediction). Would this be appropriate, or would you like to see something more about factors that impact housing value (ie from a real estate website)?

**Comment by ksedivyhaley** [comment]
Ah, I see. Yes, that's OK. I overlooked it because it wasn't in the "References" list at the bottom of the report.

For Milestone 4, please make sure that all the sources you link to in the text of your report are included in the reference list. For example, I also note that [your data](https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html) requests you cite: Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions, Statistics and Probability Letters, 33 (1997) 291-297.

(Having something about factors that impact housing value would also be a good reference to have, but not necessary for this report.)

**Comment by slbsolomon** [comment]
Hi Kate,

These items were addressed in #70 

I added an about section to the README and deleted the proposal information. The references are at the bottom of the README.
