### ISSUE TITLE
Milestone 3: Code Quality

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#59]
- Makefile needs documentation: 
  - comments throughout
  - brief summary at the top of each file that answers who wrote it, when it was written and what it does.
- Documentation [in the download script](https://github.com/UBC-MDS/DSCI_522_GROUP_312/blob/v0.3.0/scripts/load_data.py) should include example URL  (noted in previous issue)
- All scripts should include, in their individual documentation, suggested paths, eg in an Example.
- Tests - check!

**Comment by slbsolomon** [comment]
Hi Kate, I thought we had agreed in the previous feedback that the example URLs weren't necessary for this particular project. I realize that we took the information out of the README, but looking at Tiffany's example, she neither has this in the README or in her documentation. Here was her milestone 3 commit:
https://github.com/ttimbers/breast_cancer_predictor/tree/58eb063f8d43af9bfcfc5a1ba5ff96826670775f

**Comment by slbsolomon** [comment]
@EitharAlfatih may you please update the Makefile

**Comment by ksedivyhaley** [comment]
> Hi Kate, I thought we had agreed in the previous feedback that the example URLs weren't necessary for this particular project. I realize that we took the information out of the README, but looking at Tiffany's example, she neither has this in the README or in her documentation. Here was her milestone 3 commit:
> https://github.com/ttimbers/breast_cancer_predictor/tree/58eb063f8d43af9bfcfc5a1ba5ff96826670775f

Thanks for reminding me of our previous discussion - I see that now in issue #42 (note: good practice to link to related issues though unfortunately I haven't been able to do that consistently in feedback). 

Given this discussion, I will not mark off for this for Milestone 3. I will consider whether this is something you should include for Milestone 4, and get back to you in lab. I note that Tiffany's example did not include such documentation, but it's still something I'd consider best practice.

**Comment by slbsolomon** [comment]
Hi Kate,

As we discussed yesterday, we confirmed that the majority of our comments were pushed before the released was created. The final comments at the top of the make file were added in #70.

**Comment by ksedivyhaley** [comment]
Thanks for the reminder, I've made a note!
