### ISSUE TITLE
Milestone 3: Reasoning

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#61]
Overall it's great to see how you expanded your analysis in response to the known limitations / peer feedback. A few things to consider for Milestone 4:

- Having listed additional opportunities for improvement is good - could you explain some in a little more detail? For example, are there any ML models you'd like to test that you didn't have a chance to try? In what way do you expect that a feature engineering process would make features more relevant? How would you start the "more in-depth analysis" to address multicolinearity - what's your first step?
- In expanding the project, you've overcome one of your limitations re: longitude/latitude - great! Any new limitations to this analysis? This could relate to areas for improvement, but it would need to be clearly explained why it's a limitation.
- **Fix with good effect/effort ratio:** In your conclusion, repeat the numbers - what accuracy did you get (either with or without the lat/long features), and what accuracy did Chen get? It's good not to make the reader have to hunt for those key numbers.

**Comment by slbsolomon** [comment]
Hi Kate, this was addressed in #73
