### ISSUE TITLE
Visualizations feedback

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_GROUP_312#66]
Hey folks, sorry I wasn't able to give you feedback on your visualizations before lab today (I ran out of time), can you please flag me down today in the queue (just add your group number so I can get to you earlier) and I can give you some feedback in person? Sorry!

**Comment by slbsolomon** [comment]
Hi Firas,

I just saw this - if you provide viz feedback by 6PM today, I will be able to address it. Thanks!

**Comment by firasm** [comment]
I think most are captured by #60 so I can close this.
